website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, session, current_app
from flask_login import login_required, current_user
from flask_security import roles_required
import os
from .models import Note, User, Duel, Season, Groupz, Round, user_duel, user_group, user_season
from . import db
import json
from . import tabz, duels, dictionary, mysql
from datetime import datetime
from itertools import combinations
from sqlalchemy.inspection import inspect
import sqlite3
from flask import jsonify
import numbers
from sqlalchemy.inspection import inspect
from sqlalchemy import select, update
from sqlalchemy.orm import lazyload, joinedload, subqueryload
from collections import defaultdict
from itertools import groupby
import random
from random import shuffle
import mysql.connector
from . import conn
import psycopg2
import email
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, SelectMultipleField, IntegerField, RadioField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, StopValidation,NumberRange
from wtforms import DateField, DateTimeField, DateTimeLocalField
from psycopg2.errorcodes import UNIQUE_VIOLATION
from psycopg2 import errors

views = Blueprint('views', __name__)

adminz = [21, 22]
season = 1



@views.route('/', methods=['GET', 'POST'])
@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    # user_email = session.get('user_email')
    # user_id = session.get('user_id')
    # user_name = session.get('user_name')

    # dict_log = {
    #     'id': user_id, 
    #     'first_name': user_name, 
    #     'email': user_email,
    # }

    # print(myduels_user[0][0])

    groups = db.session.query(Groupz).join(
        Season).filter(Season.id == season).all()
    round = db.session.query(Groupz.round_id).filter(Groupz.season_id==season).order_by(Groupz.round_id.desc()).first()

    user_group = db.session.query(Groupz).join(User.groupy).filter(
        User.id == current_user.id).filter(Groupz.season_id == Season.id).filter(Season.id == season).filter(Groupz.round_id == round[0]).first()
    
    myduels_user = db.session.query(Groupz.id).join(User.groupy).filter(Groupz.season_id == Season.id).filter(
        Season.id == season).filter(User.id.in_([current_user.id])).filter(Groupz.round_id == round[0]).all()
    
    print(myduels_user)
    
    # myduels_user = db.session.query(User.first_name, user_duel, Duel.round_id).filter(
    #     user_duel.c.user_id == User.id).filter(user_duel.c.duel_id == Duel.id).filter(User.id == current_user.id).all()

    # print(myduels_user)
    # if current_user.id in adminz:
    #     pass
    # else:
    #     new_ret = duels.create_user_duels_list(season, myduels_user[0][0])


    # print(myduels_user[0][0])
    players = User.query.all()
    # print(players)
    data_show_table = tabz.show_table(season, round, round[0])
    # dataAll = tabz.show_table_all()
    data_all = tabz.show_table_all()
    # round = db.session.query(Round.id).filter(Season.id==season).order_by(Round.id.desc()).first()
    round = (db.session.query(Round.id)
         .join(Season, Round.season_id == Season.id)
         .filter(Season.id == season)
         .order_by(Round.id.desc())
         .first())
    data_name_tabz = tabz.show_name_table(season, round[0])
    # print(data_show_table)
    # fooor = make_tab_list()

    if request.method == "POST" and request.form.get("duelz"):

        duelz_players = []
        # flash('Lets play!!!', category='success')

        duelz = request.form.get("duelz")
        duelz_players = request.form.get("duelz_players")

        # duel_players = db.session.query(User)\
        #          .join(User.seasony)\
        #          .filter(Duel.id.like(duelz))\
        #          .first()

        return redirect(url_for('views.duel_id', season=season, duelz=duelz, duelz_players=duelz_players))

    return render_template("home.html", user_group=user_group, groups=groups, dataAll=data_all, players=players, data_name_tabz=data_name_tabz, data_show_table=data_show_table, user=current_user, adminz=adminz)


# def make_tab_list():
#     length_tab_list = len(tabz.show_name_table(season, 2))
#     return list(range(0, int(length_tab_list)))


@views.route('/business-conditions', methods=['GET'])
# @login_required
def business_conditions():
    return render_template("business_conditions.html", user=current_user, adminz=adminz)






@views.route('/delete-note', methods=['POST'])
@login_required
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})


@views.route('/delete-duel', methods=['POST'])
@login_required
def delete_duel():
    duel = json.loads(request.data)
    duelId = duel['duelId']
    duel = Duel.query.get(duelId)
    if duel:
        db.session.delete(duel)
        db.session.commit()

    return jsonify({})


@views.route('/update-duel', methods=['POST', 'GET'])
@login_required
def update_duel():
    duelCheck = json.loads(request.data)
    data = duelCheck["duelCheck"]
    data = data.split(",")
    data = (data[0], data[1], data[2])
    print(data)

    u = update(user_duel)
    u = u.values({"checked": data[0]})
    u = u.where(user_duel.c.duel_id == int(data[1]))
    u = u.where(user_duel.c.user_id == int(data[2]))

    db.session.execute(u)
    db.session.commit()
    return jsonify({})


@views.route('/update-duel2', methods=['POST', 'GET'])
@login_required
def update_duel2():
    try:
        duelResult = json.loads(request.data)
        data = duelResult["duelResult"]
        data = data.split(",")
        # print(data)
        # calculating points
        if int(data[0]) == 6 and int(data[3]) <= 4:
            points = 2
        elif int(data[0]) == 6 and int(data[3]) == 5:
            points = 2
        elif int(data[0]) == 5 and int(data[3]) == 6:
            points = 1
        elif int(data[0]) <= 4 and int(data[3]) == 6:
            points = 0
        elif int(data[0]) == 4 and int(data[3]) == 0:
            points = 2
        elif int(data[0]) == 0 and int(data[3]) == 0:
            points = 0
        else:
            points = 0

        if int(data[3]) == 6 and int(data[0]) <= 4:
            points2 = 2
        elif int(data[3]) == 6 and int(data[0]) == 5:
            points2 = 2
        elif int(data[3]) == 5 and int(data[0]) == 6:
            points2 = 1
        elif int(data[3]) <= 4 and int(data[0]) == 6:
            points2 = 0
        elif int(data[3]) == 4 and int(data[0]) == 0:
            points2 = 2
        elif int(data[3]) == 0 and int(data[0]) == 0:
            points2 = 0
        else:
            points2 = 0

        # dataz = (int(data[0]), int(data[3]), int(points), int(data[1]), int(data[2]))
        # dataz2 = (int(data[3]), int(data[0]), int(points2), int(data[4]), int(data[5]))

        if data:
            # user1 = db.session.query(user_duel).filter(user_duel.c.duel_id == int(
            #     data[1])).filter(user_duel.c.user_id == int(data[2])).first()
            # user2 = db.session.query(user_duel).filter(user_duel.c.duel_id == int(
            #     data[4])).filter(user_duel.c.user_id == int(data[5])).first()
            # print(user1)
            # print(user2)

            u = update(user_duel)
            u = u.values({"result": int(data[0]), "against": int(data[3]), "points": int(points)})
            u = u.where(user_duel.c.duel_id == int(data[1]))
            u = u.where(user_duel.c.user_id == int(data[2]))
            u2 = update(user_duel)
            u2 = u2.values({"result": int(data[3]), "against": int(data[0]), "points": int(points2)})
            u2 = u2.where(user_duel.c.duel_id == int(data[4]))
            u2 = u2.where(user_duel.c.user_id == int(data[5]))

            db.session.execute(u)
            db.session.execute(u2)
            db.session.commit()

            return jsonify({})

    except:
        print('error')
        
        
        
        



@views.route('/season/<season>/duel/<duelz>', methods=['GET', 'POST'])
@login_required
def duel_id(season, duelz):
    
    # user_email = session.get('user_email')
    # user_id = session.get('user_id')
    # user_name = session.get('user_name')

    # dict_log = {
    #     'id': user_id, 
    #     'first_name': user_name, 
    #     'email': user_email,
    # }


    season = 1

    duel = db.session.query(User.first_name, user_duel, Duel.round_id).filter(
        user_duel.c.user_id == User.id).filter(user_duel.c.duel_id == Duel.id).filter(Duel.id == duelz).order_by(User.id.desc()).all()

    roundz = db.session.query(Round).filter(Round.season_id==season).filter(Round.open==True).order_by(Round.id.desc()).first()
    group = db.session.query(User).filter(user_group.c.groupz_id==Groupz.id).filter(user_duel.c.duel_id==duelz).filter(user_duel.c.user_id==User.id).filter(Groupz.round_id==5).first()
    print('---------------------')
    print(duel)
    print('------------------')


    return render_template("duel.html", group=group, roundz=roundz,  duel=duel, players=duelz, user=current_user, adminz=adminz)




@views.route('/season/<season>/round/<round>', methods=['GET', 'POST'])
@login_required
def duel_view(season, round):
    
    # user_email = session.get('user_email')
    # user_id = session.get('user_id')
    # user_name = session.get('user_name')

    # dict_log = {
    #     'id': user_id, 
    #     'first_name': user_name, 
    #     'email': user_email,
    # }
    season_obj = Season.query.filter(Season.id==season).first()
    new_ret = duels.create_duels_list(season, round)
    print(len(new_ret))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, minimum-scale=1, minimal-ui"
    />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <link
      rel="apple-touch-icon"
      href="{{url_for('static', filename='img/logo-icon-mobile.png')}}"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="icon" href="{{url_for('static', filename='img/logo.ico')}}" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/style.css')}}"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/3.2.0/css/bootstrap-colorpicker.min.css"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <title>{% block title %}DartsClub{% endblock %}</title>
    <meta name="description" content="DARTS CLUB" />
    <meta name="googlebot" content="index,follow" />
    <meta name="author" content="milanmartis" />
    <meta property="fb:pages" content="115401168589113" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="DARTS CLUB" />
    <meta property="og:description" content="Play with sparings" />
    <meta
      property="og:image"
      content="{{url_for('static', filename='img/logo.png')}}"
    />
    <meta
      property="og:url"
      content="https://darts-club-g2oik2cmrq-ew.a.run.app"
    />
    <meta property="og:locale" content="sk_SK" />
    <meta property="og:site_name" content="DARTS CLUB" />
  </head>
  <body>
    
    {% if current_user.id %}

    <div class="container justify-content-center w-100" align="center">

      <nav align="center" class="justify-content-center navbar navbar-expand navbar-dark fixed-bottom" >
        <div class="navbar order-1 dual-collapse2">
          <ul class="navbar-nav">

            <li class="nav-item" style="margin-right: 17px;">
              <a href="/home">
              <img
              src="{{ url_for('static', filename='img/logo-head.svg') }}"
              class="filter-green"
              width="73"
            />
              </a>
          </h1>
            </li>
            <li class="nav-item">
              <a href="/home" class="nav-item nav-link">Tables</a>
            </li>
            <li class="nav-item">
              <a href="/season" class="nav-item nav-link">
                Score
              </a>
            </li>

 
          </ul>
        </div>
        <div class="navbar-dark brand"></div>
        <div class="mx-auto order-0">
          <a class="navbar-brand mx-auto" href="#"></a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target=".dual-collapse2"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse order-3 dual-collapse2 justify-content-end" style="text-aling:right; float:right;">
          <ul class="navbar-nav  text-end">
            <li
              class="nav-item justify-content-end"
            >
             <font class="username_text" style="opacity: 0.7;font-size: 90%;text-decoration: none;">
              <a href="{{ url_for('auth.user_details') }}">{{user.first_name}}</a> 
             </font> 
              <a href="{{ url_for('auth.user_details') }}">
                <i class="fa fa-user fa-sm" style="font-size:116%;padding:6px;margin-right: 10px;"></i>
              </a>
            </li>
          </ul>
        </div>
      </nav>
      {% endif %}
      
      {% with messages = get_flashed_messages(with_categories=true)
      %} {% if messages %} {% for category, message in messages %} {% if
      category == 'error' %}
      <div class="alert alert-danger alter-dismassable fade show" role="alert">
        <div class="alert {{ category }}">{{ message|capitalize }}</div>
      </div>
      {% else %}
      <div class="alert alert-success alter-dismassable fade show" role="alert">
        <div class="alert {{ category }}">{{ message|capitalize }}</div>
      </div>

      {% endif %} {% endfor %} {% endif %} {% endwith %}
         {% block content %} {%
        endblock %} {% include "footer.html" %}

    </div>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <script
      src="https://code.jquery.com/jquery-3.6.3.min.js"
      integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/3.2.0/js/bootstrap-colorpicker.min.js"></script>


  </body>
</html>

website/templates/duel.html
{% extends "base.html" %} {% block title %}DartsClub - Duel{% endblock %} {%
  block content %}
  <h1 align="center">
    <div class="container-fluid pl-0 pr-0">
      <div class="row justify-content-center mb-6">
{% for gru in group.groupy %}
{% if gru.round_id==duel[0][9]%}
<button
onclick="javascript:location.href='{{url_for('views.duel_view', season=duel[0][8],groupz=gru.id,round=duel[0][9])}}';"
class="btn4 btn-outline-dark mt-4 shadow-none"
>
BACK
</button>
{% endif %}
{% endfor%}

      </div>
    </div>
    <br />
    <img
      src="{{ url_for('static', filename='img/matchup.svg') }}"
      class="filter-green"
      width="220"
    />
  </h1>
  <div class="container-fluid pl-2 pr-8 readinglazy">
    <div class="row justify-content-center text-center">
      {% for player in duel %}
      <div valign="middle" align="center" class="col">
        <form
          method="POST"
          id="updateResult[{{loop.index}}]"
          action="javascript:;"
        >
          <input
            type="hidden"
            id="duel_id[{{loop.index}}]"
            name="duel_id[{{loop.index}}]"
            value="{{player[2]}}"
          />
          <input
            type="hidden"
            id="user_duel_id[{{loop.index}}]"
            name="user_duel_id[{{loop.index}}]"
            value="{{player[1]}}"
          />
          {% if not user.id in [player[1], adminz[0], adminz[1]] %} {% set conf2 = "opacity:0.5;" %}{% else %}{% set conf2=
            "opacity:1;" %} {% endif %}
          {% if player[9]!=roundz.id %}{% set disabled = "disabled" %} {% endif %}
          {% if not user.id in [player[1], adminz[0], adminz[1]] %}  {% set
          disabled= "disabled" %}{% set conf= "btn-result" %}{% else %}{% set conf=
          "btn-result" %} {% endif %}
          <select
            {{disabled}}
            class="custom-select"
            id="user_duel_result[{{loop.index}}]"
            id="user_duel_result[{{loop.index}}]"
            name="user_duel_result[{{loop.index}}]"
            style="height: 140px;{{conf2}}"
          >
            {% for o in range(7) %} {% if player[3] == o %}
            <option value="{{o}}" selected>{{o}}</option>
            {% else %}
            <option value="{{o}}">{{o}}</option>
            {% endif %} {% endfor %}
          </select>
          <!-- <input
            class="form-control form-control-lg resultscore"
            type="number"
            id="user_duel_result[{{loop.index}}]"
            name="user_duel_result[{{loop.index}}]"
            autocomplete="off"
            value="{{player[2]}}"
            style="height: 140px;"
          /> -->
          <h1 id="player-name-result[{{loop.index}}]">
            {{player[0] | upper | replace("_"," ")}}
          </h1>
          <button
            type="submit"
            {{disabled}}
            class="{{conf}} btn-outline-dark mt-4 btn-block shadow-none text-center"
            onClick="updateDuel2({{loop.index}})"
            id="updateDuelButton[{{loop.index}}]"
          >
            SUBMIT
          </button>
          <br />
          <div class="conntainer mt-20">
            <div class="row justify-content-center pt-20">
              <form method="POST" id="checkForm[{{loop.index}}]">
                <br />
                <input
                  type="hidden"
                  id="duel[{{loop.index}}]"
                  name="duel[{{loop.index}}]"
                  value="{{player[2]}}"
                />
                <input
                  type="hidden"
                  id="player[{{loop.index}}]"
                  name="player[{{loop.index}}]"
                  value="{{player[1]}}"
                />
                {% if player[9]!=roundz.id %}{% set disabled = "disabled" %} {% endif %}
                {% if not user.id in [player[1], adminz[0], adminz[1]] %} {% set
                  disabled = "disabled" %} {% endif %} {% if player[6] == 'false' or
                player[6] == null or player[6] == '' %} {% set ch = "unchecked"
                %}{% set confirm = "confirm" %} {% else %} {% set ch = "checked"
                %} {% set confirm = "" %} {% endif %}
                <center>
                <input
                  type="checkbox"
                  class="form-control-check"
                  {{ch}}
                  {{disabled}}
                  id="checked[{{loop.index}}]"
                  name="checked[{{loop.index}}]"
                  value="{{player[6]}}"
                  onClick="updateDuel({{loop.index}})"
                />
                </center>
              </form>
            </div>
         
            <div style="{{conf2}}" id="confirmed[{{loop.index}}]">
              <h4>
                {{confirm}}
              </h4>
            </div>
          </div>
        </form>
      </div>
      {% endfor %}
    </div>
  </div>
  
  {% endblock %}

website/templates/duels.html
{% if user.id %}
<h1 align="center">
    <img
      src="{{ url_for('static', filename='img/my-duels.svg') }}"
      class="filter-green"
      width="200"
    />
  </h1>
  {% for duell in duels %} 
              
  <div class="container readinglazy" align="center">
    <div class="row" style="display:block;max-width:320px; text-align: center;">
      {% for duel in duell %} 
      {% if not user.id in [duel.useride[0].user_id,
        duel.useride[1].user_id, adminz[0], adminz[1]] %} {% set disabled =
        "disabled" %} {% else %} {% set disabled = "" %} {% endif %} {% if 'true' ==
        duel.checking[0].checked and 'true' == duel.checking[1].checked %} {% set
        checked = "btn btn-outline-dark btn-block shadow-none" %} {% else %} {% set
        checked = "btn2 btn-outline-dark btn-block shadow-none" %} {% endif %}

  
      <div valign="middle" align="center"  class="col-12">
        <form method="POST" action="javascript:;">
          <input type="hidden" id="duelz" name="duelz" value="{{duel.duel_id}}" />
          <button id="location_href_season/{{season}}/duel/{{duel.duel_id}}" name="location_href_season/{{season}}/duel/{{duel.duel_id}}" onclick="locationHref('season/{{season}}/duel/{{duel.duel_id}}')" type="submit" {{disabled}} class="{{checked}}">
            <div class="row">
                  <div class="col-5" style="text-align: right;padding: 0px; margin: 0px;">
                    
                    {{duel.player[0].first_name | upper }}
                  </div>
                  <div class="col-2" style="text-align: center;padding: 0px; margin: 0px;">
                    
                   {{duel.result_[0].result}} : {{duel.result_[1].result}} 
  
                  </div>
                  <div class="col-5" style="text-align: left;padding: 0px; margin: 0px;">
                   {{duel.player[1].first_name | upper}}
  
                  </div>
            </div>
          </button>
        </form>
      </div>
  
      {% endfor %}
      
      
      
      
    </div>
  </div>
  {% endfor %}
  </div>
{% else %}
<div class="container">
  <div class="row">
    <div class="col">
      <h1>NO DUELS YET</h1>
    </div>
  </div>
</div>
{% endif %}

website/templates/duels_filter.html
{% extends "base.html" %} {% block content %} {% block duels_filter %}

<h1 align="center">
  <img
    src="{{ url_for('static', filename='img/duels.svg') }}"
    class="filter-green"
    width="250"
  />
</h1>
<h6><a href="{{url_for('views.season_manager', season=season_obj.id)}}">{{season_obj.name}}</a> | Round #{{round}}</h6>
{% if groups %}
<div class="container readinglazy" align="center">
  <div class="row" style="display:block;max-width:360px; text-align: center;">

    {% set groupz = request.args.get('groupz') %}
      <div
        id="carouselTabs"
        class="carousel slide"
        data-bs-ride="carousel" data-bs-touch="true" data-bs-interval="false"
      >
          <div class="carousel-indicators">
            
            {% for gro in groups %}
            {% if groupz|int == gro.id %}{% set active2 = 'active' %}{% else %}{% if 1==loop.index and groupz|int < 1 %}{% set active2 = 'active' %}{% else %}{% set active2 = '' %}{% endif %}{% endif %}
            <button type="button" class="btn text {{active2}}" data-bs-target="#carouselTabs" data-bs-slide-to="{{loop.index0}}" aria-label="Slide {{loop.index}}">{{gro.shorts}}</button>
            {% endfor %}
          </div>
          <center>
            <div class="carousel-inner carouse-duels-height">
            {% for g in groups %}
            <div class="carousel-item  {% if groupz|int == g.id %}active{% else %}{% if 1==loop.index and groupz|int < 1 %}active{% else %}{% endif %}{% endif %}"  style="align-items: center;height: fit-content;">
              {% for duell in duels %} 
              
              <div class="container readinglazy" align="center">
                <div class="row" style="display:block;max-width:320px; text-align: center;">
                  {% for duel in duell %} 
                  {% if duel.groupy[0].groupz_id == g.id %}
                  {% if not user.id in [duel.useride[0].user_id,
                    duel.useride[1].user_id, adminz[0], adminz[1]] %} {% set disabled =
                    "disabled" %} {% else %} {% set disabled = "" %} {% endif %} {% if 'true' ==
                    duel.checking[0].checked and 'true' == duel.checking[1].checked %} {% set
                    checked = "btn btn-outline-dark btn-block shadow-none" %} {% else %} {% set
                    checked = "btn2 btn-outline-dark btn-block shadow-none" %} {% endif %}

              
                  <div valign="middle" align="center"  class="col-12">
                    <form method="POST" action="javascript:;">
                      <input type="hidden" id="duelz" name="duelz" value="{{duel.duel_id}}" />
                      <button id="location_href_season/{{season}}/duel/{{duel.duel_id}}" name="location_href_season/{{season}}/duel/{{duel.duel_id}}" onclick="locationHref('season/{{season}}/duel/{{duel.duel_id}}')" type="submit" {{disabled}} class="{{checked}}">
                        <div class="row">
                              <div class="col-5" style="text-align: right;padding: 0px; margin: 0px;">
                                
                                {{duel.player[0].first_name | upper }}
                              </div>
                              <div class="col-2" style="text-align: center;padding: 0px; margin: 0px;">
                                
                               {{duel.result_[0].result}} : {{duel.result_[1].result}} 
              
                              </div>
                              <div class="col-5" style="text-align: left;padding: 0px; margin: 0px;">
                               {{duel.player[1].first_name | upper}}
              
                              </div>
                        </div>
                      </button>
                    </form>
                  </div>
              
                  {% endif %}
                  {% endfor %}
                  
                  
                  
                  
                </div>
              </div>
              {% endfor %}
              </div>
              {% endfor %}
          </div>
      </div>
        
  </div>
</div>
{% else %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>NO GROUPS YET</h1>
    </div>
  </div>
</div>
{% endif %}



<br />
<!-- <div class="container">
  <div class="row">
    <div class="col-12">
      {% for duel in duels %} 
      <h1>
        {% if loop.index == 1 %}A{% endif %}
        {% if loop.index == 2 %}B1{% endif %}
        {% if loop.index == 3 %}B2{% endif %}
        {% if loop.index == 4 %}C1{% endif %}
        {% if loop.index == 5 %}C2{% endif %}
      </h1>
      {% endfor %}
    </div>
  </div>
</div> -->
{% if duels %}

{% else %}
<div class="container">
  <div class="row">
    <div class="col">
      <h1>NO DUELS YET</h1>
    </div>
  </div>
</div>
{% endif %}

{% endblock %} {% endblock %}

website/templates/footer.html
<div class="container">
    <br />

  <div class="row align-items-center justify-content-center">
  <div class="col-12 align-items-center justify-content-center" style="width:100%; text-align: center;">
    <a href='/'>

      <img
      src="{{ url_for('static', filename='img/sipka-2.svg') }}"
      width="100px"
      class="filter-foot"
      
      />
    </a>
  </div>

  <div class="footer-text">
    <center>
        <h5>©4nolimit. Powered by appdesign.sk</h5>
    </center>
 </div>
</div>
</div>


<br />
<br />
<br />
<br />
<br />